# Default values for perforce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lff0305/perforce
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2020.2"

service:
  type: ClusterIP
  port: 1666

pvc:
  size: 128Gi

nodeSelector: {}

tolerations: []

affinity: {}
